### PR TITLE
Allow direct routing for Symfony proxy purge requests

### PR DESCRIPTION
**Pull request by Toflar**
Complementary PR for https://github.com/FriendsOfSymfony/FOSHttpCache/pull/419

TODO
* [x] Adjust to FOSHttpCache changes
* [x] Add documentation
* [x] Update CHANGELOG

### CODE REVIEW

**Comment by dbu** [comment]
this will be a new feature, so we will have to bump the branch-alias to 2.3, and also require the FOSHttpCache library in a new minor version so that class exists.

**Comment by Toflar** [comment]
Regarding the docs: They seem outdated, no? `class AppCache extends EventDispatchingHttpCache` for example. I think that is a trait now? Maybe that should be cleaned up first before we document the new feature (not sure if we need to document a lot here anyway because the proxy configuration is already properly documented in the library and all that's left here is to enable it using a configuration flag so I'd probably just link).

Redgarding the config: Do you know by chance how I can make the `http` config section in the bundle conditional? I mean it has to be there except for if you set `use_kernel_dispatcher` to `true`.

**Comment by Toflar** [comment]
No idea why travis doesn't run here but ready for review :)

**Comment by dbu** [comment]
looks good to me!

- please add documentation in the configuration reference: http://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/proxy-client.html#symfony
- can you please add some tests for the unhappy case when configuration is incomplete, to be sure we do get the error if server is not configured?

**Comment by Toflar** [comment]
Done. Still not sure about the docs references but I hope you can fix them if they're wrong 😃

**Comment by dbu** [comment]
pleaes change the branch alias in composer.json, and also change the minimum version of http-cache to 2.3 so that we are sure that we have the kernel dispatcher available.

**Comment by Toflar** [comment]
Done :)

**Comment by dbu** [comment]
i solved the merge conflict (in the changelog) and moved the KernelDispatcher documentation of FOSHttpCache into its own subsection in https://github.com/FriendsOfSymfony/FOSHttpCache/commit/cf09b88153b09e692aba9aa6ac98dbb50f0fc837 . i tweaked the documentation a bit to hopefully be more clear what needs to be done where, and merged it as 2c337377f7bf2b6bf6aef16aedee215f45f390fa

thanks for the contribution. want to write a blogpost about this? i think a fully fleshed out example would be useful.

**Comment by dbu** [comment]
oh, and for the record about cross project links: we need a label to link to, its neither page name nor heading name: https://github.com/FriendsOfSymfony/FOSHttpCache/commit/59a658246d8565fb52b365664f13e623cafc254a

**Comment by Toflar** [comment]
Thanks! I'm not blogging (yet).

**Pull request closed without merging**
