### PR TITLE
Fix readthedocs code highlighting

### PR DESCRIPTION
**Pull request by alexander-schranz**
This should hopelly fix the code highlighting in the docs:
based on: https://github.com/sphinx-doc/sphinx/issues/3215#issuecomment-368623135

### CODE REVIEW

**Comment by dbu** [comment]
oh, have not noticed but we don't highlight anymore :-(

thanks, looks like you are probably right. can you please add the extension as e requirement to
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Resources/doc/requirements.txt as well, to make the build succeed?

**Comment by dbu** [comment]
thanks a lot!

**Comment by dbu** [comment]
hm, seems not to help. i can't see in https://readthedocs.org/projects/foshttpcachebundle/builds/ what is wrong. the phpdomain extension seems to get installed. do you want to ask the readthedocs people on twitter if they have an idea why we get no highlighting?

**Comment by alexander-schranz** [comment]
locally it looks good for me but I used the current version of the read the docs theme maybe update the theme version?

**Pull request merged**
