### PR TITLE
PHP 8.0 Compatibility

### PR DESCRIPTION
**Pull request by dbu**
pushing #551 to this repo in the hope that travis-ci then sees it again.

### CODE REVIEW

**Comment by dbu** [comment]
oh, `Builds have been temporarily disabled for public repositories due to a negative credit balance.`
sigh, guess its time to move to github actions :-(

**Comment by Yoann-TYT** [comment]
Hello @dbu :) 
Seems to be okay for merge ?

**Comment by dbu** [comment]
the problem is that we don't get any travis-ci builds anymore because aparently it is "used up". it said it would replenish last week, but seems it did not. meanwhile the "plan page" only gives a tiny "There was an error" message.

so i think we need to rewrite the .travis-ci.yml to github actions to see if the tests build or not. while this looks nice and green, the phpunit tests are not executed at all, so i am not sure if it works. if somebody has time to rewrite the tests, awesome, otherwise i try to do it when i find time for it.

**Comment by dbu** [comment]
fixed in #555

**Pull request closed without merging**
