### PR TITLE
when sessions are not enabled, the listener does not exist either

### PR DESCRIPTION
**Pull request by dbu**
fix problem introduced in #435, replace #444

### CODE REVIEW

**Comment by dbu** [comment]
@Tobion can you please check if this fixes the problem you encountered?

**Comment by Tobion** [comment]
Works 👍

**Comment by emodric** [comment]
@dbu @Tobion Does this need to be backported to 1.4 branch too?

**Comment by emodric** [comment]
1.3 cannot be installed on Symfony 4.x, so that's not an issue. That's why I didn't include #439 in the first place.

The only open question is about Symfony 3.4.

**Comment by dbu** [comment]
ah good. but this change is relevant for 3.4 as well.

the listener expects the symfony session listener to exist. if sessions are not enabled, this is not the case, and container can't be compiled.

**Comment by emodric** [comment]
Okay, do you want me to backport this as well?

**Comment by dbu** [comment]
if you have the time, sure. i don't want to actively maintain version 1 anymore, but as the rest has been backported it would make sense to now also fix the regression (of not working without sessions anymore).

**Comment by emodric** [comment]
Okay. Will do it in a day or two! :+1:

**Pull request merged**
