### PR TITLE
Cleanup tag handling

### PR DESCRIPTION
**Pull request by dbu**
wrap up #218 

/cc @chtipepere

### CODE REVIEW

**Comment by dbu** [comment]
@chtipepere may i ask you to one more time check with your setup if this branch will work as expected?

**Comment by dbu** [comment]
please also check if leaving the tags enabled setting alone (so, "auto") works now as it should without raising any errors.

**Comment by ddeboer** [comment]
:+1:

**Comment by chtipepere** [comment]
I'll try this later today.

**Comment by chtipepere** [comment]
I've checkout the PR, and test in my app and... everything works as expected.
Also, removing the `tags` key in the yml works like a charm.

And if I force `tags` to `enabled: true`, then an exception is thrown:
`You can not enable cache tagging with symfony`

Thank you;)

**Comment by dbu** [comment]
thanks a lot for reporting the issue and helping to fix it! i will tag a new dot release now.

**Comment by ddeboer** [comment]
Thanks @chtipepere for testing thoroughly and helping us with fixing this!

**Pull request merged**
