### PR TITLE
php 8 and github workflow

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by ausi** [comment]
Thank you @dbu !

Is it possible to release 2.10.0 soon? ☺️

**Comment by leofeyer** [comment]
A version 2.9.2 would also help. 😊

**Comment by dbu** [comment]
i would love to get #556 in before tagging. if that did not happen by monday, i will tag for just the php 8 support.

as we increase the lowest php version, i prefer to do a minor version and not just a patch release. that leaves us the option of doing security patch releases for people on older php versions, if necessary.

**Comment by leofeyer** [comment]
That absolutely makes sense. 👍🏻

**Comment by dbu** [comment]
we managed to wrap it up, https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/2.10.0 is released

**Comment by leofeyer** [comment]
Thank you! 🎉

**Pull request merged**
