### PR TITLE
disable doccheck and test with php 7.4

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by dbu** [comment]
@ausi i wanted to start with disabling the doccheck and noticed that we don't test php 7.4

it seems either some edge case handling or some testing setup fails with 7.4 because it is more strict about array keys... can you start by looking into this? i bet that also fails with php 8...

**Comment by ausi** [comment]
I will. Can I integrate these changes into my PHP 8.0 PR?

**Comment by dbu** [comment]
yes sure, happy if you integrate them.

**Comment by dbu** [comment]
fixed in #555

**Pull request closed without merging**
