### PR TITLE
chore: replace stylecy with php-cs-fixer

### LINKED ISSUE #623: Replace styleci with php-cs-fixer
I'd suggest we replace styleci with php-cs-fixer to make it easier for auto-formatting during local development

Similar as done in FOSHttpCache in commit https://github.com/FriendsOfSymfony/FOSHttpCache/commit/944b8598a34c3485073895fa9685a79cdfbc35cf

### PR DESCRIPTION
**Pull request by usu**
fixes #623

`.php-cs-fixer.dist.php` is copied 1:1 from FOSHttpCache

### CODE REVIEW

**Comment by dbu** [comment]
thanks for this as well!

did you forget to add `.php-cs-fixer.dist.php` to the commit? i don't see it, and php-cs-fixer is complaining.

i will remove the hook for styleci once we merge this.

**Comment by usu** [comment]
> did you forget to add `.php-cs-fixer.dist.php` to the commit? i don't see it, and php-cs-fixer is complaining.

🤣 yeah, of course I did. fixed now.

**Review by dbu — APPROVED** [review]
fantastic :tada:

**Comment by dbu** [comment]
i tagged the [library](https://github.com/FriendsOfSymfony/FOSHttpCache/releases/tag/3.0.0) and the [bundle](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/3.0.0)

thanks a lot @usu for the help to push this over the finishing line!

btw, i think you are a fellow swiss web dev :-) we have a user group in zürich that occasionally meets: https://www.meetup.com/de-DE/sfugzh/
we also are always looking for talks, so if you want to share something that would be very welcome. but just attending is great too!

**Pull request merged**
