### PR TITLE
remove hacks to avoid failure due to deprecations

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by ddeboer** [comment]
Hm, Scrutinizer now fails because of my #215. The problem is that there’s no way to influence the order of builds on Travis (as far as I’m aware), so when the code coverage build ends up last, we’re way over Scrutinizer’s timeout. I suggest we just raise that timeout to 10 mins. or so.

**Comment by dbu** [comment]
can you change scrutinizer timeout in the configuration panel?

**Comment by ddeboer** [comment]
You can try to set it in this PR:

```yml
external_code_coverage:
        timeout: 600    # Timeout in seconds.
```

**Comment by ddeboer** [comment]
Thanks! Nice to get rid of the hacks. I’ll tweak code coverage in a separate PR.

**Comment by stof** [comment]
Actually, I think jobs are started in the order they are listed in the travis config

**Pull request merged**
