### PR TITLE
add spell checking and fix spelling errors

### PR DESCRIPTION
**Pull request by dbu**
following the pattern of https://github.com/FriendsOfSymfony/FOSHttpCache/pull/166 i add spell checking to the bundle doc as well.

### CODE REVIEW

**Comment by dbu** [comment]
rebased on master. this should now be green.

**Comment by ddeboer** [comment]
Docs still failing because of a very minor error. Can you fix it?

**Comment by dbu** [comment]
fixed the issues. i hope this is green now.

**Comment by ddeboer** [comment]
Yes, looks good. Still failing, but that’s been fixed in #202.

**Comment by ddeboer** [comment]
Thanks!

**Pull request merged**
