### PR TITLE
[1.3] Decorate default Symfony session listener for Symfony 3.4+ to restore user context functionality

### PR DESCRIPTION
**Pull request by emodric**
Backport of #435 to v1.3

Let's see what happens.

@Toflar I hope you don't mind, I squashed your commits.

### CODE REVIEW

**Comment by Toflar** [comment]
> @Toflar I hope you don't mind, I squashed your commits.

I‘m pro whatever makes people happy :)

**Comment by emodric** [comment]
@dbu @Toflar Finally green (and also fixed an unrelated failing test)!

I've added Symfony 3.4 to test matrix for relevant tests only, since 1.3 does not officially support 3.4 and most of other tests don't work.

**Comment by dbu** [comment]
Cheers! https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/1.3.14

**Comment by emodric** [comment]
Thanks @dbu! :tada:

**Pull request merged**
